### ISSUE TITLE
Dashboard Init failed

### ISSUE THREAD

**Issue by chirshan** [raintank/worldping-app#98]
Everytime I open the Endpoint dashboard I get an Error Message:
![bildschirmfoto 2016-05-12 um 08 25 16](https://cloud.githubusercontent.com/assets/13982472/15205859/16ecba7c-181b-11e6-91e6-fcb896cb0dda.png)

**Comment by mattttt** [comment]
@chirshan Which dashboard in particular is this? The Endpoint Summary? Or any of the Endpoint dashboards?

**Comment by chirshan** [comment]
@mattttt It's the Endpoint Summary Dashboard.
There aren't any Errors in the logfile, so I cannot give any futher information.

**Comment by mattttt** [comment]
We've gotten ~5 reports of the following error when loading endpoint dashboards, the main commonality seems to be that Grafana is behind a firewall, however they have been successfully able to add endpoints - so it isnt blocking all traffic to worldping-api.

@woodsaj I think we need your help here, @torkelo tried to lend a hand but didnt have much insight.

**Comment by woodsaj** [comment]
This is odd.  The error indicates that the graphite find query to populate the template vars failed.  But the green hearts in the screenshot indicate that the API queries to get the check health worked, so the user can reach the worldping-api backend and has a valid apiKey.

Really need the to see the request/response from a browser developer console to identify the specific query that is failing and the failure mode.

**Comment by torkelo** [comment]
they also mentioned that making a new api key solved the issue, which is also pretty strange :)

**Comment by chirshan** [comment]
so if you guys need anything from me, say it :)
I live in germany, so it can take some time when I answer, but I will :)

**Comment by woodsaj** [comment]
@chirshan we believe that this issue was due to a bug in Grafana which was fixed in the latest release (3.0.3).  Can you try upgrading to the latest grafana and seeing if the problem is now resolved.

**Comment by chirshan** [comment]
@woodsaj I've updated Grafana to 3.0.4 and the problem still appers.

**Comment by torkelo** [comment]
Yes,  I don't think this is a grafana issue or at least it looks like an api error or communication issue.

**Comment by digrich** [comment]
Not specific to WorldPing but I think we can reproduce this issue on any grafana dashboard.

Steps to reproduce : 

Grafana Version - 3.0.3
DB - OpenTSDB

- Create query template and select 'On Dashboard Load' refresh option. Save it
- Come back and change the same query template to custom,  add some data and save it. 
- Reload the dashboard and it shows this error.

It looks, though we have custom query template, it still tries to refresh internally from the query template.

**Comment by chirshan** [comment]
Did you made any progress here? 
The problem still exists.

**Comment by woodsaj** [comment]
@torkelo i have just been troubleshooting this more and this definitely looks like a core grafana issue.  What leads me to that conclusion is that every type of datasource failure i have deliberately triggered, 500 response, 400 response, timeout etc.. results in the error message being set with a valid reason, eg "Dashboard init failed
Template variables could not be initialized: Internal Server Error"

So the "cannot read property 'message' of null" is because promise returned from templateValuesSrv.updateOptions() is being rejected with a null reason.
https://github.com/grafana/grafana/blob/1ea54049d07c4cc7959e20a6f9b6ffde24e670b4/public/app/features/templating/editorCtrl.js#L108

i am not sure where exactly that is coming from though

**Comment by dragonxtek** [comment]
I have the same issue with Grafana 3.1.1

![selection_101](https://cloud.githubusercontent.com/assets/10552658/19002891/9ba96f9e-8724-11e6-8eab-5edbdc9c300e.png)

![selection_102](https://cloud.githubusercontent.com/assets/10552658/19002894/a0c76ca6-8724-11e6-95bb-034b887811ff.png)

**Comment by nopzor1200** [comment]
I think this problem was resolved. A bit hard to track down, but the fix went into Grafana 3.1.x. If anyone is still seeing it, please let us know.

**Comment by IrmantasM** [comment]
I have a similar issue in Saas Grafana but with 'data':

![image](https://user-images.githubusercontent.com/21358910/76747001-58adba80-6770-11ea-9852-d8d51bc0ef70.png)

![image](https://user-images.githubusercontent.com/21358910/76747111-8a268600-6770-11ea-91b5-c3552732a51a.png)

**Comment by simonc6372** [comment]
It is unlikely that this is related to the issue reported nearly 4 years ago. If you are a worldPing customer, please raise a support ticket at support@grafana.com in the first instance.
